### ISSUE TITLE
Update Site Not Reachable

### ISSUE THREAD

**Issue by schulzp** [anb0s/EasyShell#1]
Hi, apparently the [update site](http://pluginbox.sourceforge.net/) is not reachable anymore. SourceForge had an outage a couple of weeks ago could this be the cause? Maybe publishing the update site on github might be an alternative.

**Comment by anb0s** [comment]
Thanks for reporting this! I've moved the update site to "http://anbos.de/eclipse/pluginbox-updatesite/" and updated the main page.

**Comment by anb0s** [comment]
see http://anb0s.github.io/EasyShell/ too

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.
