### ISSUE TITLE
Menu contains each item twice on Mac OS (by default)

### ISSUE THREAD

**Issue by kwin** [anb0s/EasyShell#102]
Each menu item appears twice in the menu by default on EasyShell 2.0.0 for Mac OS. The label of the duplicate entries is <something> and <something> v1.4.x. The triggered action is for both items the same. This happens even for a brand new workspaces. Only after clicking on "Restore Defaults" in Preferences->EasyShell->(1) Menu the entries with the v1.4.x suffix get removed.

**Comment by anb0s** [comment]
It should only happen if EasyShell 2.0 detects old preferences created by previous installed EasyShell 1.x versions. Then EasyShell should ask you first time "If you want to import / convert the old entries". Then it creates the default entries from EasyShell 2.0 and additionally the converted entries from version 1.x. Then the user can verify the old entries and delete them manually if he wants or just restore defaults.

So it should not happen in new workspaces and without using EasyShell 1.x before. I cannot reproduce it at Linux and Windows.

Have you seen this "migration" dialog at first startup?

Thanks!

**Comment by anb0s** [comment]
@kwin: still wonder how to reproduce. Have you seen this "migration" dialog at first startup?

**Comment by kwin** [comment]
I have never seen any migration dialog and can reproduce with a new workspace. Even for that the old and new handlers are active. In which scope is the preference store you leverage for detecting an upgrade (http://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/runtime/preferences/IScopeContext.html)? Probably there is something broken with that mechanism.

Some background:
I have installed "Eclipse IDE for Java Developers (Neon)  through the Eclipse Installer (Oomph) , then launched a new workspace and afterwards installed EasyShell via the p2 update site. After a restart both entries are visible (1.4.x and new).

Hopefully you are able to reproduce with these steps.

**Comment by anb0s** [comment]
Thanks! I've catched the issue at Linux Debian too:
![image](https://cloud.githubusercontent.com/assets/95811/19982310/e1e8da20-a205-11e6-9864-8d853d1d8c0a.png)

I will investigate...

**Comment by anb0s** [comment]
please use new build #111
