### ISSUE TITLE
After copied file path, a tool-tip "Copied to clipboard" always exists.

### ISSUE THREAD

**Issue by vector090** [anb0s/EasyShell#103]
See attachment. That tool-tip keeps appearing everywhere (editor, status bar, side panel...), whenever my mouse stops, which is very annoying.

![easyshell-issue](https://cloud.githubusercontent.com/assets/3281148/19924079/64debd28-a125-11e6-82c1-8387e2d97aa6.png)

Eclipse version:
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

Installed plugins: viPlugin; GoClipse;

**Comment by anb0s** [comment]
Thanks for reporting this! I saw this under Linux (Debian Stretch 9.0) with XFCE last week too. No problem at Windows and Mac OS X. Can you confirm that it's at GTK+ based desktop system (XFCE, Gnome etc. @Linux) ? Please give me some information about your OS, desktop etc.

**Comment by vector090** [comment]
Thanks for the promp reply! My OS is ubuntu server 14, with gnome metacity as window manager, xfce-panel as task panel. This can be considered basically gnome desktop environment.
------------------ Original ------------------

**Comment by anb0s** [comment]
Just found that SWT at GTK has a "int DELAY = 8000;". It means the "auto-hide=true" that i've enabled creates a timer with 8 seconds and then hides the tool-tip. It must be a way shorter at windows etc. I will verify that when i'm back @homeoffice late today...

May be you can verify if the sticky tool-tip goes away after ~8 seconds...

[source]: https://searchcode.com/file/109822648/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/ToolTip.java

**Comment by vector090** [comment]
Indeed it goes away after a while. But what's annoying is it keeps appearing when mouse moves even a bit.
 Is it ok to add an option to choose whether to show this tool-tip? It seems not necessary for everyone.
------------------ Original ------------------

**Comment by anb0s** [comment]
Yes, it's annoying! I will fix it for GTK and add an preference option for this additionally. The tooltips are also shown in case of execution errors etc. --> for this cases they are maybe still needed...

**Comment by vector090** [comment]
Thanks. Looking forward to your new release! 
------------------ Original ------------------

**Comment by anb0s** [comment]
A new test build is available with a preliminary fix, but not yes tested with Linux at all (have only windows machine here). I'm just using other way to show tooltips (SWT JFace instead of Widget) with 3 seconds delay for hide --> so "keeps appearing when mouse moves" may be still there! I will test it soon at my linux debian machine...

The option for using tooltips at all needs more time and will be done later for v2.1

I you want to try, see #104

**Comment by anb0s** [comment]
I've verified it under Debian Stretch and it works now with build from #104. I will close this issue, because it's fixed and add options etc. with #105 Thanks for report and fast replies!
