### ISSUE TITLE
keys binding conflict with old version ?

### ISSUE THREAD

**Issue by hand515** [anb0s/EasyShell#114]
What's the meaning of below error ? 

I have installed v1.4 , and already uninstalled before install the new version.

```
!SUBENTRY 1 org.eclipse.jface 2 0 2016-11-24 15:16:57.997
!MESSAGE A conflict occurred for ALT+F1:
Binding(ALT+F1,
	ParameterizedCommand(Command(de.anbos.eclipse.easyshell.plugin.commands.clipboard,EasyShell Clipboard,
		,
		Category(de.anbos.eclipse.easyshell.plugin.commands.category,EasyShell,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@367e0b0e,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,user)
Binding(ALT+F1,
	ParameterizedCommand(Command(com.tetrade.eclipse.plugins.easyshell.command.copyPath,,
		,
		,
		,
		,,false),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,user)

```

**Comment by anb0s** [comment]
Hello,
the new key bindings are different and i've no idea yet. ALT+F1 was not used by EasyShell. 2.0 defines this:
...
Alt + E: Main popup menu (Windows)
Alt + Shift + E: execute multiple commands for selection(s)
Shortcuts that executes the command directly if only one defined or opens a popup menu like Alt + E reduced for category:

Alt + O: Open Here (shell)

Alt + R: Run with (shell)

Alt + X: Explore

Alt + C: Copy to Clipboard

Alt + U: User defined category

Special not available for all OS:

Alt + D: Open with Default application
...

Please check key bindings in your eclipse settings --> filter for EasyShell. May be you can ad more information, screenshot etc. then. Thanks!

**Comment by hand515** [comment]
Thanks,
I think I have fixed it by cleaning all datas about "com.tetrade.eclipse.plugins.easyshell" in .eclipse\org.eclipse.oomph.setup\setups\user.setup , and Restoring default KEYS.

**Comment by anb0s** [comment]
I did not found how the old plugin id "com.tetrade.eclipse.plugins.easyshell" can affect the new setting with id "de.anbos.eclipse.easyshell.plugin"... very strange... I will close this one if it happens again i will try to go deeper... thanks!
