### ISSUE TITLE
EasyShell context menu option not showing in STS 3.8.4.RELEASE Navigator View

### ISSUE THREAD

**Issue by gitgrimbo** [anb0s/EasyShell#151]
### Package View

![image](https://user-images.githubusercontent.com/1020541/27515544-78749b4c-599d-11e7-80ed-a82492d15c0d.png)

### Navigator View

![image](https://user-images.githubusercontent.com/1020541/27515540-6beb3340-599d-11e7-8fb4-7b63410c4414.png)

### STS version

![image](https://user-images.githubusercontent.com/1020541/27515532-399a7720-599d-11e7-8f2a-b9911caf5e0a.png)

**Comment by anb0s** [comment]
Thanks for reporting. I see the same here with Eclipse 4.6.x. All other views (like C/C++ Projects, Package- or Project-Explorer) are working. Please use Keyboard shortcuts like "Alt+E" or "Shift+Alt+E" etc. as workaround. I will investigate...

**Comment by anb0s** [comment]
Verified that group.open is not available in Navigator view. In this group we create the EasyShell menu. We are creating the main menu via plugin.xml and have no possibility to check this error. Other group like additions can be used or alternative main menu creation should be done programmatically.

**Comment by bostone** [comment]
I'm on Eclipse Version: 2018-12 (4.10.0) Build id: 20181214-0600 running on macOS Mojave v. 10.14.3 and there's no EasyShell in the dropdown menu. I'm using build 2.1.0.v20170508-1844 or pretty much what you get from the Eclipse Marketplace currently. Shows up in Project and Package explorers
![image](https://user-images.githubusercontent.com/395020/54213864-6025ee00-44a2-11e9-9ff5-d4e8012701fe.png)

**Comment by anb0s** [comment]
Yes, it's not working, because of "group.open is not available in Navigator view". I've tried some solutions, but then need special handling only for the navigator view and it makes simple code complex for other views...

**Comment by anb0s** [comment]
I have still no easy solution for this...

**Comment by anb0s** [comment]
OK, i've found a solution for this:

Project Explorer:
![image](https://user-images.githubusercontent.com/95811/93687704-ea033e00-fabf-11ea-8b82-418d30e1dc4c.png)

Package Explorer:
![image](https://user-images.githubusercontent.com/95811/93687720-03a48580-fac0-11ea-8032-f45d8fe3568e.png)

C/C++ Projects:
![image](https://user-images.githubusercontent.com/95811/93687672-b1fbfb00-fabf-11ea-8ef9-c09bc44a2e92.png)

Navigator:
![image](https://user-images.githubusercontent.com/95811/93687730-2d5dac80-fac0-11ea-8f27-300d4580659b.png)

As you see for all views except Navigator it is located near "Open" or "Show In" and for Navigator it's llocated as addition below.
I hope it's ok ;)

Anyway the classic Navigator view is deprecated with Eclipse 2020-06 and will be removed, so this solution should work for all Eclipse versions until then.

**Comment by anb0s** [comment]
Please check this out with new testing #179
