### ISSUE TITLE
Open iTerm here doesn't work properly any more (doesn't switch to the project folder)

### ISSUE THREAD

**Issue by marco-brandizi** [anb0s/EasyShell#152]
The feature to right click on a folder in Eclipse and having it opened on iTerm was great. Now it doesn't work any more, iTerm opens a new session, but remains in my home. the default command configured in easyShell (`open -a iTerm ${easyshell:container_loc}`) doesn't seem good.

OS X: 10.12.5
iTerm2: Build 3.1.beta.5
EasyShell: 2.1.0.v20170508-1844
Eclipse: Neon.1a Release (4.6.1) Build id: 20161007-1200

**Comment by anb0s** [comment]
Thanks for reporting!

What is the version of EasyShell that you had before or that worked?

**Comment by marco-brandizi** [comment]
Sorry, I don't remember, but I last time I have updated it to the last version was months ago, September or October.

**Comment by anb0s** [comment]
Sorry i've no MacOSXand need more information about the error. Please provide. Do you know other "command line" parameters to open a shell or run script at MacOSX?

**Comment by marco-brandizi** [comment]
@anb0s, no sorry. I can only tell you that, if I type this from the macos terminal: `open -a iTerm /tmp`, it opens a  new iTerm2 session, but it totally ignores /tmp, I'm always on my home dir.

**Comment by anb0s** [comment]
@marco-brandizi so this is an issue with iterm, not EasyShell. Can you please try this:
`open /tmp -a iTerm`

found, here: https://apple.stackexchange.com/questions/148508/how-to-open-a-new-tab-in-iterm-in-the-same-folder-as-the-one-that-is-open

**Comment by anb0s** [comment]
I've found in iTerm2 docu:

> Working directory
> Normally, new sessions begin in your home directory. You can choose to open new sessions in the same directory as the current session (but only when creating a new tab), or you can specify a starting directory.
> 

see: https://iterm2.com/documentation-one-page.html

**Comment by anb0s** [comment]
Sorry i cannot reproduce this, please investigate again reopen and help me...
