### ISSUE TITLE
Easy Shell dosen't works in Eclipse Oxygen

### ISSUE THREAD

**Issue by zrwlc2008** [anb0s/EasyShell#154]
Easy Shell dosen't works in Eclipse Oxygen (v1.4 , v2.1)

**Comment by anb0s** [comment]
v1.4 supports versions until included 4.5
v2.x supports all versions from 3.8 to 4.7

**Comment by anb0s** [comment]
I hope v2.1 works for you with Oxygen (4.7)

**Comment by zrwlc2008** [comment]
It works after I added EasyShell from Eclipse marketplace . Thanks , EasyShell is a quite useful tool , it helps me a lot .
