### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by batarian71** [anb0s/EasyShell#163]
Hello ! I contribute to open source software in my free time. Do you want me to make a logo for EasyShell?

It will be perfect for the readme file.

**Comment by paulvi** [comment]
There already one used for marketplace https://marketplace.eclipse.org/content/easyshell

**Comment by anb0s** [comment]
Thanks, i have already handmade logo with retro pixels style ;)
https://github.com/anb0s/EasyShell/blob/master/plugin/images/easyshell100.png
So i'm OK with it and will add it to readme.

But i'm open for new logo if you want to contribute! Thank You!

**Comment by batarian71** [comment]
I made a more iconic logo in consideration of the available logotype. Simple and elegant. A stronger logo. Also describe if you have a shape you like.


![sadasd](https://user-images.githubusercontent.com/36008612/40832233-98db21c8-6593-11e8-8fd7-902f6eed8a8b.jpg)

**Comment by anb0s** [comment]
Thank You, it looks good!
    Do you have svg file that can be commited and may be converted to
      png?
    --
Regards
Andre (anb0s)
eMail: anb0s@anbos.de
    Am 01.06.2018 um 11:02 schrieb
      batarian71:
    
    
      I made a more iconic logo in consideration of the available
        logotype. Simple and elegant. A stronger logo. Also describe if
        you have a shape you like.
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/anb0s/EasyShell/issues/163#issuecomment-393819027","url":"https://github.com/anb0s/EasyShell/issues/163#issuecomment-393819027","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anb0s/EasyShell","title":"anb0s/EasyShell","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/anb0s/EasyShell"}},"updates":{"snippets":[{"icon":"PERSON","message":"@batarian71 in #163: I made a more iconic logo in consideration of the available logotype. Simple and elegant. A stronger logo. Also describe if you have a shape you like.\r\n\r\n\r\n![sadasd](https://user-images.githubusercontent.com/36008612/40832233-98db21c8-6593-11e8-8fd7-902f6eed8a8b.jpg)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/anb0s/EasyShell/issues/163#issuecomment-393819027"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [anb0s/EasyShell] Logo Design (#163)",
"sections": [
{
"text": "",
"activityTitle": "**batarian71**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@batarian71",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"anb0s/EasyShell\",\n\"issueId\": 163,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"anb0s/EasyShell\",\n\"issueId\": 163\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/anb0s/EasyShell/issues/163#issuecomment-393819027"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341212019\n}"
}
],
"themeColor": "26292E"
}
    
    
  



	
		
			
				
			
		
		
			
				Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
				www.avast.com

**Comment by anb0s** [comment]
> I made a more iconic logo in consideration of the available logotype. Simple and elegant. A stronger logo. Also describe if you have a shape you like.

Thank You, it looks good!

Do you have svg file that can be commited and may be converted to png?

**Comment by batarian71** [comment]
Okey. I sent a pr

https://github.com/anb0s/EasyShell/pull/165

**Comment by anb0s** [comment]
Thanks! I've merged and updated the marketplace site.

**Comment by paulvi** [comment]
How about favicon for https://anb0s.github.io/EasyShell/ ?

**Comment by paulvi** [comment]
Also menu icon and other icons should be similar in style IMHO 

compare

https://github.com/anb0s/EasyShell/blob/master/Logo/icon.png

and

![](https://raw.githubusercontent.com/anb0s/EasyShell/master/site/images/EasyShell_2.0_context_menu_windows.png)

**Comment by anb0s** [comment]
Yes the site was updated too, here it's shows the image:
https://github.com/anb0s/EasyShell/blob/gh-pages/index.md
but not here: https://anb0s.github.io/EasyShell/
strange...

**Comment by anb0s** [comment]
For icons i need PNG format 16x16 and for about dialog size 32x32...
