### ISSUE TITLE
open in Explorer from "Open Resource" window

### ISSUE THREAD

**Issue by AlBundy33** [anb0s/EasyShell#164]
If you press ctrl+shift+r to open a resource it would be nice if th context menu of the resources would have an entry to directly open them in explorer.

Currently I use "Show In -> Package Explorer" and use EasyShells "Open in Explorer" as second step.

**Comment by anb0s** [comment]
Yes, that would be good to have one step solution!

I will investigate how to contribute to the "Open Resource" dialog...

**Comment by anb0s** [comment]
May be related to #74

**Comment by anb0s** [comment]
try new test build #180
