### ISSUE TITLE
add linux 'nemo' file browser

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#17]
copied from: https://sourceforge.net/p/pluginbox/feature-requests/18/
-------

x:~$ nemo --help
Aufruf:
nemo [OPTION …] [Adresse …]
Browse the file system with the file manager
Hilfeoptionen:
-h, --help Hilfeoptionen anzeigen
--help-all Alle Hilfeoptionen anzeigen
--help-gtk GTK+-Optionen anzeigen
Anwendungsoptionen:
-c, --check Eine Reihe schneller Selbsttests durchführen.
--version Die Versionsnummer des Programms anzeigen.
-g, --geometry=GEOMETRIE Das erste Fenster mit den angegebenen Ausmaßen (z.B.: 900x600) erstellen.
-n, --no-default-window Nur für ausdrücklich angegebene Adresse die Fenster erstellen.
--no-desktop Den Schreibtisch nicht verwalten (die Einstellungen im Einstellungsdialog ignorieren).
-q, --quit Nemo beenden.
--display=ANZEIGE X-Anzeige, die verwendet werden soll

**Comment by anb0s** [comment]
Explore command: nemo {2}

**Comment by anb0s** [comment]
Some tipps & tricks to get info about used file browser:
http://forums.linuxmint.com/viewtopic.php?f=42&t=130919

**Comment by anb0s** [comment]
In LMDE 201403
$ xdg-mime query default inode/directory
will print:
nemo.desktop
or
nautilus.desktop

**Comment by anb0s** [comment]
how to detect the desktop:
http://askubuntu.com/questions/125062/how-can-i-find-which-desktop-enviroment-i-am-using
http://unix.stackexchange.com/questions/116539/how-to-detect-the-desktop-environment-in-a-bash-script

**Comment by anb0s** [comment]
how to detect the default file (directory) browser:
http://forums.linuxmint.com/viewtopic.php?f=42&t=130919

**Comment by anb0s** [comment]
howto get some information about default tools (xdg):
https://wiki.ubuntuusers.de/xdg-utils?redirect=no#xdg-open

**Comment by anton-johansson** [comment]
I understand that this should be fixed, so it automatically detects nemo and opens it. But is there a way to force a command with EasyShell, for example ```nemo %p```?

**Comment by anton-johansson** [comment]
Nevermind, not sure how I missed it.

**Comment by anb0s** [comment]
Yes, just replace one of the commands, e.g. "Unknown shell...": Explore command: nemo {2}

I the next version it will be more consistent:
- i will provide more known tool configurations
- there will be table with "selected" tools (preset)
- the most used file browsers and shells / terminals will be detected and pre-selected at first start of new plugin
- user can change or create own presets and add more predefined or own defined tools, so it's not fixed anymore to 4 possible commands, you can have more or less, e.g.
  - nemo
  - thunar
  - sakura terminal
  - other terminal
  - copy path
  - my own tool 1
  - my own tool 2
  -...

**Comment by anb0s** [comment]
see issue #9 too

**Comment by anb0s** [comment]
done at branch v2_0
