### ISSUE TITLE
Can not install EasyShell from Marketplace

### ISSUE THREAD

**Issue by stefaneidelloth** [anb0s/EasyShell#170]
## Expected Behavior
Installation should work with Eclipse 2018-12

## Actual Behavior
I get following error:

HTTPServer Unknown HTTP Response Code
...Moved Permanently

**Comment by anb0s** [comment]
I've investigated the issue, but cannot reporoduce. here the version and steps as screenshots:
```
Eclipse IDE for C/C++ Developers
Version: 2018-12 (4.10.0)
Build id: 20181214-0600

```
![image](https://user-images.githubusercontent.com/95811/52563864-d6332880-2e02-11e9-96fd-5a46d61d3062.png)

Open Marketplace client + Install:
![image](https://user-images.githubusercontent.com/95811/52563944-0a0e4e00-2e03-11e9-9d0c-a724f1691e3f.png)

Accept:
![image](https://user-images.githubusercontent.com/95811/52563956-185c6a00-2e03-11e9-8a01-c91cc563d150.png)

After Eclipse restart:
![image](https://user-images.githubusercontent.com/95811/52563974-2316ff00-2e03-11e9-97b0-437c62cd5584.png)

May be it was a problem at GitHub server? Try again...

**Comment by anb0s** [comment]
Cannot reproduce and no response from originator --> closing, please reopen if still a problem.
