### ISSUE TITLE
RFE: Change License to EPL 2.0

### ISSUE THREAD

**Issue by stefan-prange** [anb0s/EasyShell#172]
## Expected Behavior
The file LICENSE.txt that comes with the plugin's sources shows the EPL v2.0, as available here:
https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt

The motivation for suggesting to switch from EPL, v1.0, to EPL, v2.0, are the changes that come with v2.0, as summarized here: https://en.wikipedia.org/wiki/Eclipse_Public_License#Version_2.0
Especially the removal of the "choice of law" provision is quite important for the company that I work for.

## Actual Behavior
The file LICENSE.txt contains the text of the EPL, v1.0.

## Steps to Reproduce the Problem
Just open the file LICENSE.txt and read its first line, which says "Eclipse Public License - v 1.0":
https://github.com/anb0s/EasyShell/blob/master/LICENSE

## Your Environment

- Plugin version: **2.1.0.v20170508-1844**
- Eclipse Version: **2019-06 (4.12.0)**
- Java Version: **Oracle jdk-11.0.3**
- Operating System Version: **Windows 10**

**Comment by anb0s** [comment]
I've already planed to switch to v2.0 --> thank you form the reminder ;)
