### ISSUE TITLE
Change default command for cygwin

### ISSUE THREAD

**Issue by AlBundy33** [anb0s/EasyShell#173]
The current default command for cygwin is
C:\cygwin\bin\bash.exe
this should be changd to
C:\cygwin\bin\mintty.exe
because this is the default for the created shortcut from cygwin-setup.

Maybe you can change it directly to
C:\cygwin64\bin\mintty.exe
because I'ld assume that most users are using the 64-bit version.

If I use C:\cygwin64\bin\bash.exe (on latest Windows 10) I have some issues.
For example I get a segmentation fault if I run ls
With mintty.exe there seems no issue.

**Comment by anb0s** [comment]
Thanks for the report!

I'm not using cygwin anymore (switched to MSYS2), but can just adapt the default command to "C:\cygwin64\bin\mintty.exe" if you can test it for Open Shell in the "working dir" and Run shell script.

**Comment by AlBundy33** [comment]
I've changed the default entry in my configuration - I've just created the issue because maybe others have this problem too.

Furthermore "C:\cygwin64\bin\mintty.exe" would be a good default for my default-installation. :-)
(this is also the default-path from cygwin-setup)
