### ISSUE TITLE
Short-Cut Alt+R in conflict with Eclipse-Main-Menu Run Short-Cut Alt+R

### ISSUE THREAD

**Issue by makkimesser** [anb0s/EasyShell#181]
The key-binding of Alt+R to EasyShell-Run is in conflict with the Eclipse-Main-Menu Run, that also has binding to Alt+R.

I know, I can unbind it in `Preferences, Keys`. But I have more that one Eclipse-Instance and have to do this for each again.
I would suggest to change the binding to a short-cut, that is not in conflict with the Eclipse-Main-Menu.

**Comment by anb0s** [comment]
Yes, see this issues also and it's annoying. Should be fixed for 2.2

**Comment by anb0s** [comment]
I will change it to "Alt+Shift+R" - any objections?

**Comment by makkimesser** [comment]
In some Editors (e.g. Java-, Lua-Editor) Alt+Shift+R is used for Refactor-Rename elements. What about to use Ctrl-Alt-R?

**Comment by anb0s** [comment]
"Ctrl+Shift+R" is used for "Open Ressource" and lot of other commands are using "Ctrl+Shift+" pattern already - this is why i've used "Alt+" for all commands and also ""Alt+Shift+E" for "Multi Selection".

Hm, i do not see conflict with "Alt+Shift+R" in Java-Editor etc. I'm using "Eclipse IDE for Java Developers" and also "Eclipse IDE for C/C++ Developers". What is your distribution or can you provide more information?

**Comment by makkimesser** [comment]
Concerning Alt+Shift+R see [https://www.vogella.com/tutorials/EclipseShortcuts/article.html](https://www.vogella.com/tutorials/EclipseShortcuts/article.html) under 7. Refactoring Section.

I use Eclipse JEE-Distribution "Eclipse IDE for Enterprise Java Developers" from [https://www.eclipse.org/downloads/packages/release/2020-12/r/eclipse-ide-enterprise-java-developers](https://www.eclipse.org/downloads/packages/release/2020-12/r/eclipse-ide-enterprise-java-developers)

It is difficult to find a Short-Cuts that's meaningfull but unused :-(.
What about to add an Entry to the Main-Eclipse Run-Menu?

**Comment by makkimesser** [comment]
I tested V2.2.0.v20210403 and I found that the binding Alt-Shift-R is now in conflict with the Java-Editor Refactor-Rename, see my comment above.

**Comment by anb0s** [comment]
Yes, i know :( I will check this "shortcuts" topic together with #175 until v2.2 final release and hope to find something that does not collide with most Eclipse distributions...

**Comment by anb0s** [comment]
"Alt + Shift + R" is just working in all my installations - i do not see any conflicting binding...

**Comment by makkimesser** [comment]
Concerning Alt+Shift+R see https://www.vogella.com/tutorials/EclipseShortcuts/article.html under 7. Refactoring Section.

**Comment by anb0s** [comment]
Yes sure, but how can i trigger this? I've tried all the perspectives and this binding is just working for EasyShell Run and does not show the rename refactoring as expected. There is no shortcut shown in menu:
![image](https://user-images.githubusercontent.com/95811/118437515-0e60fa00-b6e3-11eb-976b-91525220d813.png)

Anyway i will use another schema for all commands like "Alt + E" for EasyShell and then additional letter for sub command:
![image](https://user-images.githubusercontent.com/95811/118438156-2be29380-b6e4-11eb-954f-10167f2fc215.png)

**Comment by makkimesser** [comment]
Open JavaEditor, place Cursor on ClassName, then context-menu:
![image](https://user-images.githubusercontent.com/362621/118443911-c2b34e00-b6ec-11eb-8ce6-1bbde64f9c08.png)

Open JavaEditor, place Cursor on ClassName, then main-menu refactoring:
![image](https://user-images.githubusercontent.com/362621/118443984-dc549580-b6ec-11eb-97b7-22b78f2baae6.png)

**Comment by makkimesser** [comment]
The shortcuts with Alt+E, R seems a good decision and has, as minimal conflicts:
![image](https://user-images.githubusercontent.com/362621/118444957-1a05ee00-b6ee-11eb-9552-6b8fe04c228f.png)

**Comment by anb0s** [comment]
see Release v2.2.0
