### ISSUE TITLE
Administrator Terminal (Command Prompt or Window Powershell)

### ISSUE THREAD

**Issue by reach009** [anb0s/EasyShell#185]
## Expected Behavior
To have an option to add Command Prompt or Window PowerShell terminal as administrator access.

## Actual Behavior
I haven't found a way to do it yet.

## Steps to Reproduce the Problem
N.A

## Your Environment

- Plugin version: 2.1.0.v20170508-1844	
- Eclipse Version: 2.3.400.v20201202-1800
- Java Version: 11
- Operating System Version: Window 10 Home Edition
- Desktop Version: Gigabyte

**Comment by anb0s** [comment]
I've found how to do it via powershell.exe here: [open-cmd-as-admin-with-windowsr-shortcut](https://superuser.com/questions/968214/open-cmd-as-admin-with-windowsr-shortcut) with the UAC warning still in-place, so you have to accept dialog always.

# Windows Administrator Terminal
## Command Prompt
### Create a new command for cmd admin terminal: `powershell.exe "Start-Process cmd -Verb RunAs"`
- go to menu `Window -> Preferences -> EasyShell -> (2) Command`
- enter `prompt` in the search field
- select `Command Prompt` and use `Copy...` button
- in the new dialog 
  - rename to `Command Prompt as Admin` or similar
  - select `Working directory` checkbox
  - Change command to `powershell.exe "Start-Process cmd -Verb RunAs"`
![image](https://user-images.githubusercontent.com/95811/109027578-3d0d9c80-76c1-11eb-9315-ce016be96667.png)
- accept with `OK`
### Create new menu with the command
- go to menu `Window -> Preferences -> EasyShell -> (1) Menu`
- Use `Add...` button
- enter Filter `admin`
- select `Open - Command Prompt as Admin (User)`
![image](https://user-images.githubusercontent.com/95811/109029446-236d5480-76c3-11eb-946a-0375f9b35bd5.png)
- accept with `OK`

## Powershell Prompt
### Create a new command for powershell admin terminal: `powershell.exe "Start-Process powershell -Verb RunAs"`
- go to menu `Window -> Preferences -> EasyShell -> (2) Command`
- enter `powershell` in the search field
- select `PowerShell` and use `Copy...` button
- in the new dialog 
  - rename to `PowerShell as Admin` or similar
  - select `Working directory` checkbox
  - Change command to `powershell.exe "Start-Process powershell -Verb RunAs"`
![image](https://user-images.githubusercontent.com/95811/109028006-aab9c880-76c1-11eb-9c8b-654a03bc045a.png)
- accept with `OK`
### Create new menu with the command
- go to menu `Window -> Preferences -> EasyShell -> (1) Menu`
- Use `Add...` button
- enter Filter `admin`
- select `Open - PowerShell as Admin (User)`
![image](https://user-images.githubusercontent.com/95811/109029446-236d5480-76c3-11eb-946a-0375f9b35bd5.png)
- accept with `OK`

**Comment by anb0s** [comment]
Added to Wiki [Create special commands](https://github.com/anb0s/EasyShell/wiki/Create-special-commands)

Please check this out and give me feedback 👍

**Comment by reach009** [comment]
> Added to Wiki [Create special commands](https://github.com/anb0s/EasyShell/wiki/Create-special-commands)
> 
> Please check this out and give me feedback 👍

Hi @anb0s,

Thank you for your quick response. I followed all the steps you posted above and it works. However, the working directory is always WINDOWS\system32\ by default once I open it as admin access. 

Is there a way I can change it to the current working directory (my code dir). 

![image](https://user-images.githubusercontent.com/35024397/109109900-1b6bee00-7771-11eb-9131-421eda209ddf.png)

**Comment by anb0s** [comment]
Hi @reach009,

OK, i see, it worked, because i've started my eclipse as admin to avoid the UAC warning dialog during testing. It looks like the problem is known and can be solved, see [start-process-workingdirectory-as-administrator-does-not-set-location](https://stackoverflow.com/questions/43494863/start-process-workingdirectory-as-administrator-does-not-set-location)

We can try this solution :)

**Comment by anb0s** [comment]
This is working for powershell admin console:

Please change the `PowerShell as Admin` command to `powershell.exe -command "Start-Process powershell -Verb RunAs -ArgumentList '-NoExit', '-Command', 'cd ${easyshell:container_loc}'"`

![image](https://user-images.githubusercontent.com/95811/109144127-14d57a80-7761-11eb-9946-df2379afaf9a.png)

**Comment by reach009** [comment]
> This is working for Powershell admin console:
> 
> Please change the `PowerShell as Admin` command to `powershell.exe -command "Start-Process powershell -Verb RunAs -ArgumentList '-NoExit', '-Command', 'cd ${easyshell:container_loc}'"`
> 
> ![image](https://user-images.githubusercontent.com/95811/109144127-14d57a80-7761-11eb-9946-df2379afaf9a.png)

Thank you so much for your help. It works!!! @anb0s

**Comment by anb0s** [comment]
You are welcome 👍 

I will add this as preset for the next version, see #186 and #187

**Comment by reach009** [comment]
> You are welcome 👍
> 
> I will add this as preset for the next version, see #186 and #187

Cool man, looking forward to it.

**Comment by anb0s** [comment]
Updated Wiki: https://github.com/anb0s/EasyShell/wiki/Windows-Administrator-Terminal

**Comment by anb0s** [comment]
pushed new testing build see #192
