### ISSUE TITLE
Cannot rest/restore default settings

### ISSUE THREAD

**Issue by mlieberwirth** [anb0s/EasyShell#188]
## Expected Behavior
**With a click on button "Restore Defaults" all changes are undone.**

## Actual Behavior
**In my case nothing. If I click the button nothing happens**
I accidentally changed the first menu-item (open command prompt here). After this change all short-cuts are gone and nothings happens if I use context-menu to "open command prompt here" on project-folder.
I tried to uninstall and install EasyShell, but settings are still same (and it does not work.)
I run/installed a new Eclipse version (2020-12-R), but unfortunately both eclipses share some data. After installing EasyShell I got same miss-configured behavior :-(
Maybe it would help to know where the configuration is stored in windows and remove it?!?

## Steps to Reproduce the Problem
* Edit... configuration of the menu "open command prompt here"
* try to get ride of this change... for example with "Restore Defaults"

## Your Environment

- Plugin version: **2.1.0**
- Eclipse Version: **2020-09 and 2020-12**
- Java Version: **11**
- Operating System Version: **Win10**

**Comment by anb0s** [comment]
Thank You for your report! I will investigate the issues with "Restore Defaults".

As workaround please exit Eclipse and remove the file in your workspace: `.metadata\.plugins\org.eclipse.core.runtime\.settings\de.anbos.eclipse.easyshell.plugin.prefs`

After restart the defaults should be restored and loaded.

**Comment by anb0s** [comment]
If i use "Restore Defaults" button, is shows this question:
![image](https://user-images.githubusercontent.com/95811/109508526-3c4d7f80-7aa0-11eb-91ed-0ff820063c3e.png)
Use "Yes" button and all menu items are resetted. Now you can still cancel with `Cancel `button or `Apply `with apply button.

**Comment by anb0s** [comment]
If you have changed one of the commands (used in menu) via `Edit` menu and `Edit `command. You should see The Remove button enabled:
![image](https://user-images.githubusercontent.com/95811/109509591-53d93800-7aa1-11eb-94a7-00302a95bad0.png)

and via `Remove `you can remove the user defined changes for the command and restore default command.

**Comment by mlieberwirth** [comment]
> Thank You for your report! I will investigate the issues with "Restore Defaults".
> 
> As workaround please exit Eclipse and remove the file in your workspace: `.metadata\.plugins\org.eclipse.core.runtime\.settings\de.anbos.eclipse.easyshell.plugin.prefs`
> 
> After restart the defaults should be restored and loaded.

Thanks a lot for the fast answer.  Yes that helps and yes, if this info is in workspace a reinstall of eclipse would not help.
I did the other stuff from UI and it did not help, but your workaround saves my day.

Thanks for the nice plugin.
