### ISSUE TITLE
Reset all commands to inital values

### ISSUE THREAD

**Issue by laurentmuller** [anb0s/EasyShell#198]
## Expected Behavior
It will be nice if it was possible to reset all commands to the initial values (as when first installed the plugin).

## Actual Behavior
This function does not exist.

## Steps to Reproduce the Problem
I have modified some commands and now it is not more working as expected.

## Your Environment
- Plugin version:   2.2.1.v20210716-0745
- Eclipse Version:  2021-09 (4.21.0)
- Java Version: 11.0.8
- Operating System Version: Windows 10 Professionnel v21H1

**Comment by anb0s** [comment]
Thanks, just use the `Restore Default` button in preferences:
![image](https://user-images.githubusercontent.com/95811/139727004-19aab66d-ae5c-4279-bc90-9dd30f085665.png)

`Yes`
![image](https://user-images.githubusercontent.com/95811/139727029-082a379b-2193-416f-89b4-d751d4674ba6.png)

Now you see default menu entries:
![image](https://user-images.githubusercontent.com/95811/139727287-56db1f54-f67b-41ce-acc6-c20a648326fb.png)

And context menu:
![image](https://user-images.githubusercontent.com/95811/139727141-482c971f-36ea-4538-af6e-28f5717e7abe.png)

**Comment by anb0s** [comment]
above will only restore your menu entgries but not overwritten commands, you can do the same for the commands (used by menu entries) too:
![image](https://user-images.githubusercontent.com/95811/139727577-3629297c-b371-4197-a972-d4c196e1931b.png)

**Comment by laurentmuller** [comment]
I didn't see the Restore Defaults button.
Thank You.

**Comment by anb0s** [comment]
Just a hint: if you have changed one command you should see the state as `Plugin+User`. You can just restore this one command to Plugin defaults, please select the command and use the `Remove...` button:

![image](https://user-images.githubusercontent.com/95811/139729124-460bed88-1a8a-43d8-b0b2-6239c9c20ed1.png)

![image](https://user-images.githubusercontent.com/95811/139729200-c6ed8c9b-f696-41d9-8180-b141c9ce8838.png)

![image](https://user-images.githubusercontent.com/95811/139729338-84161f11-7f2c-470d-badc-2287e390e74b.png)
