### ISSUE TITLE
Add PowerShell version 7

### ISSUE THREAD

**Issue by laurentmuller** [anb0s/EasyShell#199]
## Expected Behavior
Replace commands using the PowerShell version 5  by the version 7.

## Actual Behavior
All PowerShell commands use the version 5. 

## Your Environment
- Plugin version:   2.2.1.v20210716-0745
- Eclipse Version:  2021-09 (4.21.0)
- Java Version: 11.0.8
- Operating System Version: Windows 10 Professionnel v21H1

**Comment by anb0s** [comment]
Thanks, can you please point out (links, docu, examples etc.) how the new powershell version 7 is working different to the version 5 ?

**Comment by laurentmuller** [comment]
Some links to PowerShell 7:

- General: https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs?view=powershell-7.1
- Installation on Windows: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.1

The main change is to replace `pwsh.exe` argument with the `powershell.exe` argument.

**Comment by anb0s** [comment]
- [ ] instead of `powershell.exe` now it must be `pwsh.exe`

**Comment by laurentmuller** [comment]
I have replaced all occurrences of `powershell.exe` with `pwsh.exe` and it's working !

Thank You

**Comment by anb0s** [comment]
I will add new configurations for PowerShell 7 (pwsh) this as PowerShell 5 is still the default in windows <=10 and exists in parallel to pwsh

**Comment by anb0s** [comment]
new presets added:
![image](https://user-images.githubusercontent.com/95811/149628621-ce854646-0316-494d-9841-c84638655015.png)

please checkout testing build #204

**Comment by anb0s** [comment]
@laurentmuller see new [pre-release v2.3.0-beta.2](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.2)
that also includes chnages from [pre-release v2.3.0-beta.1](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.1)

**Comment by laurentmuller** [comment]
Great Job !
