### ISSUE TITLE
Key binding on Mac OS should use other combination than the single option key (⌥)

### ISSUE THREAD

**Issue by twwwt** [anb0s/EasyShell#200]
## Expected Behavior
On Mac OS, the [option key](https://en.wikipedia.org/wiki/Option_key) (⌥) is a *key modifier* (similar to the AltGr key on Windows) used to type additional characters. For instance, on German keyboard layouts `⌥` + `e` maps to the € (Euro) currency symbol. In general, entering `⌥` + `e` on the keyboard in any Eclipse text editor should type the character it is mapped to, according to the actual keyboard layout used.

## Actual Behavior
Unfortunately, EasyShell's default keyboard binding on Mac OS generally starts with `⌥` + `e`, which makes it impossible to use `⌥` + `e` to type the character that the keyboard layout maps it to (since it is captured by EasyShell's key binding).

Please, change EasyShell's default keyboard shortcuts for Mac OS to not use the single option key `⌥` nor the `⌥` + `⇧ Shift` combination. As a proposal, it could be changed like I did on my local Eclipse installation (`^` is the `CTRL` key):

<img width="721" alt="Preferences" src="https://user-images.githubusercontent.com/143208/147410402-5a371b28-bf4c-44d9-bd72-e155e1a380cb.png">

## Steps to Reproduce the Problem
Obvious from the explanation above.

## Your Environment
- Plugin version: **2.2.1**
- Eclipse Version: **2021-12 (4.22)**
- Java Version: **17.0.1**
- Operating System Version: **Mac OS 12.1**

**Comment by anb0s** [comment]
Thanks for the report. I will investigate how to configure the keys for different platfroms (here PC or Mac). May be somebody knows it and can help with hint or better a PR ;) .

I've no Mac OS and cannot test, so test build can be provided bofore cretaing new tag (release).

**Comment by anb0s** [comment]
please checkout testing build #204

**Comment by anb0s** [comment]
@twwwt see new [pre-release v2.3.0-beta.2](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.2)
that also includes chnages from [pre-release v2.3.0-beta.1](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.1)
