### ISSUE TITLE
add substitution variable for line_number

### ISSUE THREAD

**Issue by bigla** [anb0s/EasyShell#212]
# Goal
Open the source of a derived file when debugging derived files at exact same line. Because this makes this great tool even more flexible.

# Explanation
I have some project generating **derived files** from **source files** with a different extension, without changing the file line numbers. 

I'd love to be able to open the **source file** in an external editor passing the exact same line number where I am currently at (or where warnings and errors are indicating problems) using something along the lines of:
`eclipse -name Eclipse --launcher.openFile ${easyshell:container_name}${easyshell:file_separator}${easyshell:resource_basename}.cu:${easyshell:resource_line_number}`

*Any occuring line breaks in above command not intended!*

Example files:
`derived file: myDerivedfile.cudato.cpp`
`source file: myDerivedfile.cu`

## Suggestion for a substitution variable name
`${easyshell:resource_line_number}`

**Comment by bigla** [comment]
For now I am using a bash script with the Eclipse built in "External Tools Configurations..."
(of course running without rebuilding - contact me if full configuration shall be posted here.)
configured External Tools arguments: `${selected_file} ${selected_text}`

This is of course only for my special case described above. And no error handling, nor input sanitization is done.
WARNING: This assumes the first found line containing selected content is the right one.

```bash
set -x

selected_file=$1
selected_text=$2

echo "$selected_file"
echo "$selected_text"

selected_file_no_ext=${selected_file%.cudato.cpp}

echo "$selected_file_no_ext"

line_number="$(grep -nF "$selected_text" "$selected_file" | head -n 1 | cut -d : -f 1)"

echo "$line_number"


eclipse -name Eclipse --launcher.openFile "$selected_file_no_ext".cu:$line_number

```

**Comment by bigla** [comment]
FYI:
Sounds like [Eclipse forgot about this Idea](https://bugs.eclipse.org/bugs/show_bug.cgi?id=86186).
The issue that enabled opening files @ line numbers is [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=305336)

**Comment by anb0s** [comment]
@bigla see new [pre-release v2.3.0-beta.2](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.2)
that also includes chnages from [pre-release v2.3.0-beta.1](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.1)
