### ISSUE TITLE
Any tips to run EasyShell command from other plugin?

### ISSUE THREAD

**Issue by tonyho** [anb0s/EasyShell#257]
I want to execute the easyshell commands in other plugin, but haven't found a example. Is there any?
Thanks.

**Comment by anb0s** [comment]
Hi, sorry for late answer. No  there is no example how to call them. 

I can work via command may be:
https://github.com/anb0s/EasyShell/blob/0be1e8877199bf2266cdedc8994563d6b28f531f/plugin/plugin.xml#L12

**Comment by anb0s** [comment]
the dispatch is done here: https://github.com/anb0s/EasyShell/blob/0be1e8877199bf2266cdedc8994563d6b28f531f/plugin/src/de/anbos/eclipse/easyshell/plugin/handlers/Execute.java#L31
