### ISSUE TITLE
New variable for workspace name

### ISSUE THREAD

**Issue by Joggel72** [anb0s/EasyShell#259]
## New variable for workspace name
eclipse provides the variable for the location of the workspace _${workspace_loc}_. 
To open the shell for the workspace itself it would be helpfull to add the name of workspace as title for the shell.

Is it possible to add a new variable like _${easyshell:workspace_name}_ with the name of the workspace from _Preferences -> General -> Workspace -> Show workspace name_?
As alternative a variable with the name of the folder of the workspace  _${easyshell:workspace_foldername}_. 
So if the workspace path is _/myWorkspaces/wsProject 1_  the varible will contain _wsProject 1_

**Comment by anb0s** [comment]
fixed in [v2.3.0-beta.3](https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.3)
