### ISSUE TITLE
problem installing on Eclipse MARS

### ISSUE THREAD

**Issue by yarix** [anb0s/EasyShell#27]
### Problem:
1. When installing the plugin via Eclipse Market Place or via Update Site I get this error:
**No repository found at http://anbos.de/eclipse/pluginbox-updatesite.**

### Environment
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.dsl.product

**Comment by yarix** [comment]
closing since it was probably an issue with proxy.

**Comment by anb0s** [comment]
Thanks for reporting! just tried the site and does not work!

**Comment by anb0s** [comment]
During testing of new 1.5.x alpha version the update site was broken --> fixed, only versions <= 1.4.2 should be provided now without error.

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.
