### ISSUE TITLE
org.eclipse.ui.views.navigator.ResourceNavigator cannot be found

### ISSUE THREAD

**Issue by mwensveen-nl** [anb0s/EasyShell#277]
## Expected Behavior
**See the Easyshell option in the contextmenu**

## Actual Behavior
**Easyshell option not showing, but an error in the .log (see attachment) **

## Steps to Reproduce the Problem
- clean install of Eclipse 2023‑06 R
- install easyshell through the market place

## Your Environment

- Plugin version: **EasyShell	2.2.1.v20210716-0745**
- Eclipse Version: **2023-06 (4.28.0)**
- Java Version: **eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.7.v20230425-1502/jre/bin/java**
- Operating System Version: **Ubuntu 22.04.2 LTS**

[Eclipse.log](https://github.com/anb0s/EasyShell/files/11767848/Eclipse.log)

**Comment by anb0s** [comment]
see #265 fixed at main

**Comment by anb0s** [comment]
Will be provided with next beta soon

**Comment by anb0s** [comment]
please try new beta build: https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.4

**Comment by piradix** [comment]
this update work for me. thanks

**Comment by mwensveen-nl** [comment]
> please try new beta build: https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.4

Yes this version works, thanks

**Comment by anb0s** [comment]
now released: https://github.com/anb0s/EasyShell/releases/tag/v2.3.0
