### ISSUE TITLE
Problem on Eclipse 2023-06

### ISSUE THREAD

**Issue by acirasa** [anb0s/EasyShell#278]
## Expected Behavior
Easy shell not opened on prjoect contestual menu

## Actual Behavior
**{text}**

## Steps to Reproduce the Problem
*right click with mouse on project Explorer**

## Your Environment

- Plugin version: **2.2**
- Eclipse Version: **2023-06**
- Java Version: **17**
- Operating System Version: **Windows 11**
- OPTIONAL: Linux Desktop Version: **{version}**
- OPTIONAL: External Tool Version: **{version}**

**Comment by acirasa** [comment]
duplicate

**Comment by anb0s** [comment]
#265

**Comment by anb0s** [comment]
#277

**Comment by anb0s** [comment]
please try new beta build: https://github.com/anb0s/EasyShell/releases/tag/v2.3.0-beta.4

**Comment by anb0s** [comment]
now released: https://github.com/anb0s/EasyShell/releases/tag/v2.3.0
