### ISSUE TITLE
Show EasyShell entry on maven dependencies

### ISSUE THREAD

**Issue by gsnerf** [anb0s/EasyShell#28]
When working with maven based java projects, it sometimes is necessary to jump to the jars of a dependency in the local maven repository. It would be nice if the context menu entry would show up in the package explorer for entries under "maven dependencies" so one can use the "Explore..." function.

**Comment by anb0s** [comment]
Thanks for requesting. I will look at it together with other "menue contribution" requests, see #13, #16 and others.

**Comment by anb0s** [comment]
Just tried to look at this, but cannot find "maven dependencies" in package explorer view. I'm not very familiar with maven and may be missing something. Please attach more information, e.g. screenshot or description how to see them...

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.

**Comment by anb0s** [comment]
I need more input about the "maven dependencies" in package explorer. I do not see them in my installation. What is needed to get this view? Thanks!

**Comment by gsnerf** [comment]
You need a maven project with some dependency defined in the POM (for testing purposes it should be sufficient to have junit or something alike added as a dependency). If you import the maven project to eclipse it should pick up the dependency automatically and show the "Maven dependencies" node in project view. If you add a dependency when the eclipse project already exists you need to sync the maven POM with the eclipse project (in newer eclipse versions alt+f5 should trigger that refresh).

**Comment by anb0s** [comment]
done for v2.1

![image](https://cloud.githubusercontent.com/assets/95811/21500696/c989a76e-cc41-11e6-9b17-5ea2cb868461.png)
