### ISSUE TITLE
EasyShell v1.4.2 cannot be installed in Eclipse Neon(4.6.0M5)

### ISSUE THREAD

**Issue by wanhongfu** [anb0s/EasyShell#29]
**Error message:**

_Cannot complete the install because one or more required items could not be found.
  Software being installed: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2)
  Missing requirement: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found_

My configuration: JDK 8, Mac OS X 10.11.3

**Comment by anb0s** [comment]
Thanks! First i need to use the Neon milestone, will try.

**Comment by anb0s** [comment]
Fixed for 1.5

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.

**Comment by anb0s** [comment]
done at branch v2_0
