### ISSUE TITLE
Only have - Copy Path option

### ISSUE THREAD

**Issue by straki** [anb0s/EasyShell#3]
OS X El Capitan
On Eclipse Mars 4.5.1 don't have all option from menu, only have one Copy Path.
On Eclipse Luna everithing work as expected.

![screen shot 2015-10-07 at 10 17 59 am](https://cloud.githubusercontent.com/assets/3831239/10332415/4fac3d72-6cdd-11e5-9701-dbfccf8ead7e.png)

**Comment by anb0s** [comment]
Thanks for reporting! I'm working with Windows 7 and Linux (Mint) and cannot reproduce with Mars 4.5.0. No idea now how to analyse Mac OS X...

I see the new icon before EasyShell in your screenshot, are you using the testing version 1.5.x???
What kind of file browser are you using? (Navigator, Project Explorer...)
What kind of files/ressources are affected? (Files, Folders, Jar, all of them...)
Can you enable "Debug output" in EasyShell preferences and start your eclipse with "-debug" switch and report the console output, prefixed with EasyShell?

I will try to add some more debug output for next versions...

**Comment by anb0s** [comment]
> I see the new icon before EasyShell in your screenshot, are you using the testing version 1.5.x???
I've pushed the testing (for internal use only) version 1.5.x to the new update site by mistake :( sorry, now it delete from update site...
You can remove it and install the 1.4.x version again.
Or if still you want playing with new version, it has three profiles and all of them are disabled now. So go to preferences of EasyShell -> EasyShell 0 and click at Disabled --> Enabled and select you Mac OS X preferences:
![easyshell 1 5 prefs](https://cloud.githubusercontent.com/assets/95811/10342490/8af4476c-6d19-11e5-948d-d27d551b270c.png)

**Comment by anb0s** [comment]
Just for your information if you want be an alpha tester ;)
- migration from 1.4.x is not supported yet
- property names and the menues / structure will be changed
- EasyShell instances 0, 1, 2 are only prototypes and wil be removed, instead user can arrange multiple commands and add own defined commands... stay tuned...

**Comment by straki** [comment]
It looks like I am using 1.5.0 :) I install it few days ago over update suite.

I enable this 0 and now I have what I need so I will stay in 1.5 for now.

Basically I use it to open terminal or file browser in specific location.

**Comment by anb0s** [comment]
good :) please report if something does not work for you!

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.
