### ISSUE TITLE
[v2.0] update Eclipse Marketplace

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#39]
Update Eclipse marketplace with new EPL release v2.0

**Comment by anb0s** [comment]
related to #34

**Comment by gdiamond** [comment]
I need to install v1.4.x but it's no longer available via the update site or marketplace.  It's been replaced with a beta v2.0 that I can't get to install in Mars 2.  Can a 1.4.x update site be created until 2.0.x is stable?

**Comment by anb0s** [comment]
see #69 it was to early to add now --> do it after release

**Comment by anb0s** [comment]
done
