### ISSUE TITLE
Post some screenshot may help.

### ISSUE THREAD

**Issue by crazy-canux** [anb0s/EasyShell#42]
Post some screenshot in the readme may let more people know the fetures.

**Comment by anb0s** [comment]
Thanks, yes it would be good to show the features with screenshots.

**Comment by anb0s** [comment]
Added two screenshots from version 1.4.x will be rewritten and replaced with 2.0 during release in June.

**Comment by anb0s** [comment]
close this one and prepare more for v2.0 with #43

**Comment by crazy-canux** [comment]
Got it.
