### ISSUE TITLE
[v2.0] issues found in early pre-release

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#50]
See issues found with first patch commited to v2_0 branch, see issue #45 comments from electrotype:

1. There is a NPE if you create an item and then change its "type" to "Other" (and you click "OK")

2. Would be nice to list the new names to use as arguments since "{1}", "{2}", etc. don't work anymore.

3. Another small bug: when you click the "Edit" button for an item, its "type" is always reset to "Open".

**Comment by anb0s** [comment]
_3. Another small bug: when you click the "Edit" button for an item, its "type" is always reset to "Open"._
Fixed

**Comment by anb0s** [comment]
#46

**Comment by electrotype** [comment]
Another small bug in this alpha version: when you edit an item, it doesn't keep its place, it is moved as the first item of the list.

That's it for me! I'm pretty sure you are already aware of a lot of those small bugs, but in case it helps!

Thanks again!

**Comment by anb0s** [comment]
_1. There is a NPE if you create an item and then change its "type" to "Other" (and you click "OK")_
Fixed!

**Comment by anb0s** [comment]
_4. Another small bug in this alpha version: when you edit an item, it doesn't keep its place, it is moved as the first item of the list._
Fixed!

**Comment by anb0s** [comment]
@electrotype: yes it helps :)

**Comment by anb0s** [comment]
_2. Would be nice to list the new names to use as arguments since "{1}", "{2}", etc. don't work anymore._
Added!

**Comment by anb0s** [comment]
beta 1 release will be pushed today and i need help with testing --> #52
