### ISSUE TITLE
please support https://github.com/cmderdev/cmder

### ISSUE THREAD

**Issue by mgiaco** [anb0s/EasyShell#51]

**Comment by anb0s** [comment]
Thanks for the request!

I cannot find any information about the "command line" parameters to start cmder with setting the
- working-dir
- execute script
... may be something other usable

Please provide a link to the documentation...

**Comment by anb0s** [comment]
/START or /SINGLE can be used:
cmder.exe /START "${easyshell:container_loc}"

**Comment by anb0s** [comment]
added Open
cmder.exe /START "${easyshell:container_loc}"

Run script etc. not supported...

**Comment by anb0s** [comment]
done for #78

**Comment by mgiaco** [comment]
wow thanks
