### ISSUE TITLE
eclipse SDK 4.6 install  Easy Shell   requires 'org.eclipse.core.runtime.compatibility 0.0.0' 

### ISSUE THREAD

**Issue by abcijkxyz** [anb0s/EasyShell#57]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2)
  Missing requirement: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found

**Comment by abcijkxyz** [comment]
v2.0

**Comment by anb0s** [comment]
see #30 and #45

**Comment by anb0s** [comment]
Thanks, v2.0 should address the issue, see #54 if you want to use beta release.
