### ISSUE TITLE
gnome-terminal: change to working directory does not work in LMDE 201403

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#6]
copied from: https://sourceforge.net/p/pluginbox/bugs/23/
-------

Tested with "Linux Mint Debian Edition 2014-03:
gnome-terminal: change to working directory does not work

**Comment by anb0s** [comment]
https://help.gnome.org/users/gnome-terminal/stable/

**Comment by anb0s** [comment]
see problem with gnome-terminal here too:
https://sourceforge.net/p/pluginbox/bugs/18/#ff53

**Comment by anton-johansson** [comment]
Using EasyShell in Linux Mint 17.2 Cinnamon. This does not work here either.

**Comment by anb0s** [comment]
Yes, i've the same issue here. So for the next version i've created new option to set the working-directory in environment before calling the tool, so it look like this sequence:
pushd "{1}"
gnome-terminal
popd

The environment will be set via shell script or just in Java-Runtime-Environment before calling the tool. I can provide beta version soon if you want...

**Comment by anton-johansson** [comment]
Allright, fair enough! I can live without this functionality until next version. :)

**Comment by anb0s** [comment]
It works without ", like this: gnome-terminal --working-directory={1}

**Comment by anb0s** [comment]
done at branch v2_0
