### ISSUE TITLE
marketplace shows version 2.0.0 but it cannot be installed

### ISSUE THREAD

**Issue by gdiamond** [anb0s/EasyShell#69]
v1.4.x is no longer available via Eclipse Marketplace or site URL http://anb0s.github.io/EasyShell/.  It's been replace with v2.0 that's still in beta.  I'm sure I can track down the jar in another Eclipse install but I prefer to manage my plugins using Eclipse itself.

**Comment by anb0s** [comment]
Thanks for the report. I've have no plans to remove the old versions from the update site and just verified again with Mars release, i see the old version here:
![image](https://cloud.githubusercontent.com/assets/95811/17213521/e572855c-54d4-11e6-887b-175da5f6f302.png)

The new v2.0 betas are only available at the testing site and will be moved to the main site after release...

**Comment by anb0s** [comment]
If you remove the check "Show only the latest versions of available software" the you should also see and install older versions (not compatible with Neon, but working with Mars and older 3.8 stream)...

![image](https://cloud.githubusercontent.com/assets/95811/17213561/1bbf1d28-54d5-11e6-9592-7a2230b7766d.png)

**Comment by anb0s** [comment]
If does not work for you (no idea why) the update @ sourceforge is still there:
http://pluginbox.sourceforge.net

![image](https://cloud.githubusercontent.com/assets/95811/17213764/05ee1020-54d6-11e6-9eb6-c2d6ddafadef.png)

**Comment by anb0s** [comment]
@gdiamond: please inform me if it's working for you, thanks!

**Comment by gdiamond** [comment]
Andre,

It's now working for me. I don't know what I was doing wrong.  I'll let you know if I figure it out.

On Jul 29, 2016, at 5:42 AM, Andre Bossert <notifications@github.com<mailto:notifications@github.com>> wrote:


@gdiamond<https://github.com/gdiamond>: please inform me if it's working for you, thanks!

**Comment by anb0s** [comment]
ok, thanks!

**Comment by gdiamond** [comment]
@anb0s,  
Manually adding either update site http://pluginbox.sourceforge.net or http://anb0s.github.io/EasyShell now allows me to install released versions.  Not sure why it wouldn't two days ago.

I do see a problem with installing by dragging the Install Button from https://marketplace.eclipse.org/content/easyshell.  
If I search for EasyShell and Filter by Status "Production/Stable" I have no choice but to install v2.0.  
![screen shot 2016-07-29 at 10 03 05 am](https://cloud.githubusercontent.com/assets/8548757/17254926/12274ec6-5574-11e6-8dbe-5f599be936c5.png)
![screen shot 2016-07-29 at 10 06 59 am](https://cloud.githubusercontent.com/assets/8548757/17255003/746d8640-5574-11e6-9db2-7e8b28a1edea.png)
![screen shot 2016-07-29 at 10 08 15 am](https://cloud.githubusercontent.com/assets/8548757/17255027/92fe5b02-5574-11e6-8411-53e86cc82ad5.png)

Installing via Help->Eclipse Marketplace in Mars2 I can still only choose v2.0.  I was able to capture an error message that may be of use to you.
![screen shot 2016-07-29 at 10 11 06 am](https://cloud.githubusercontent.com/assets/8548757/17255221/962e9e6c-5575-11e6-8da7-7dadb3c05334.png)
![screen shot 2016-07-29 at 10 11 52 am](https://cloud.githubusercontent.com/assets/8548757/17255223/981c0ade-5575-11e6-9ffe-229e00ae9ba2.png)

I can only guess that this is an idiosyncrasy of the marketplace and eclipse version.

Let me know if you would like me to do any other testing.  You can resolve the issue at any time.

**Comment by gdiamond** [comment]
I found the following on the Errors tab on https://marketplace.eclipse.org/content/easyshell that could be related.  I don't see errors for the times I saw errors.

`Cannot complete the install because one or more required items could not be found.
  Software being installed: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2)
  Missing requirement: Easy Shell A1:E501 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found`

**Comment by anb0s** [comment]
@gdiamond thank you! I've added the version 2.0 as alternative to marketplace to test it before releasing. Now it shows as the only version to the user but is not available now. I've removed the 2.0 from marketplace and will add next week after releasing. No you should see 1.4.2 as the last one at marketplace too!

**Comment by anb0s** [comment]
verified that 1.4.2 is available via marketplace
