### ISSUE TITLE
[v2.0] Steps to build the plugin using the source code

### ISSUE THREAD

**Issue by MGelbana** [anb0s/EasyShell#76]
Would you please provide the steps needed to build the plugin using the source code ?

**Comment by anb0s** [comment]
I've created a Wiki page with some first preliminary description:
https://github.com/anb0s/EasyShell/wiki/How-to-build

Please check it out and give me some feedback about it. If you miss something or are blocked, because it behaves different or wrong, do not hesitate to ask me. Thanks!

**Comment by anb0s** [comment]
From my point of view it's addressed now. Please comment if something is missing. Thanks!
