### ISSUE TITLE
Menu item does not appear on Luna SR 1

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#8]
copied from: https://sourceforge.net/p/pluginbox/bugs/25/
----------
Created: 2014-12-28 Creator: liturgist (https://sourceforge.net/u/liturgist/profile/):

Menu item does not appear. This is the same as issue # 21, but I do not see any way to make it "open" again.
This problem happens to me running:
Easy Shell Feature 1.4.2
on
Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800

**Comment by anb0s** [comment]
labels: --> Luna

**Comment by anb0s** [comment]
Thank you for reporting! Cannot reproduce it with my Win7 x64, Java 1.7.0_51 and 4.4.1 CDT EPP.
Please provide additional information about your system (OS, Java version etc.).
May be there are some entries in eclipse error log?

**Comment by anb0s** [comment]
liturgist (https://sourceforge.net/u/liturgist/profile/) 2014-12-30:

=== OS information
Windows 7 Professional
Service Pack 1
Microsoft Windows [Version 6.1.7601]
=== From Eclipse Help > About > Installation Details > Configuration
eclipse.vm=C:\Program Files\Java\jre1.8.0_25\bin\server\jvm.dll
eclipse.vmargs=-Dosgi.requiredJavaVersion=1.7
com.tetrade.eclipse.plugins.easyshell (1.4.2) "Easy Shell Plugin" [Starting]
Id: com.tetrade.eclipse.plugins.easyshell, Version: 1.4.2, Location: reference:file:plugins/com.tetrade.eclipse.plugins.easyshell_1.4.2.jar
=== Eclipse log
No mention of anything starting with com.tetrade...

**Comment by anb0s** [comment]
Sorry, just found the email with "moderation" request for your post from sourceforge in my spam folder and accept it. WTF :(
I just cannot reporoduce it here with Luna and Mars releases EPP C++ and EPP Java releases. No idea how to catch this now...

**Comment by anb0s** [comment]
What kind of file browser are you using? (Navigator, Project Explorer...)
What kind of files/ressources are affected? (Files, Folders, Jar, all of them...)
Can you enable "Debug output" in EasyShell preferences and start your eclipse with "-debug" switch and report the console output, prefixed with EasyShell?

I will try to add some more debug output for next versions...

**Comment by anb0s** [comment]
closed this, because no answer received. Please reopen if still a problem. Thanks!

**Comment by anb0s** [comment]
Decision to skip release of v1.5 and concentrate at v2.0 release, because of Eclipse 4.6 compatibility and new EPL license and complete new code base.

**Comment by hydrian** [comment]
This is still an issue. I'm using Eclipse Luna 4.4 classic with PDT.  I'm using the most recent allowed in market place. Looks like 1.4.2 of Easy Shell.

**Comment by anb0s** [comment]
OK, can you please answer this:

> What kind of file browser are you using? (Navigator, Project Explorer...)
> What kind of files/ressources are affected? (Files, Folders, Jar, all of them...)
> Can you enable "Debug output" in EasyShell preferences and start your eclipse with "-debug" switch and report the console output, prefixed with EasyShell? Check your error view for EasyShell or com.tetrade prefix...

**Comment by hydrian** [comment]
It was is in navigator in the PHP perspective. I'll get you the debug info when I'm in front of my machine.

**Comment by hydrian** [comment]
I only tried folders because I'm really only looking to open a terminal in the selected folder from the navigator. 

I didn't get any errors on the startup or launch of the workspace when I launched eclipse in -debug mode from the console. I did get the output of the EasyShell settings when I went to it's preferences. 

[EasyShell] Open Value      : >mate-terminal --working-directory="{1}"<
[EasyShell] Open Default    : >gnome-terminal --working-directory="{1}"<
[EasyShell] Run Value       : >mate-terminal --working-directory="{1}" --command=./''{3}''<
[EasyShell] Run Default     : >gnome-terminal --working-directory="{1}" --command=./''{3}''<
[EasyShell] Explore Value   : >caja {2}<
[EasyShell] Explore Default : >nautilus {2}<
[EasyShell] Copypath Value  : >{2}{5}<
[EasyShell] Copypath Default: >{2}{5}<

I'm using the MATE desktop environment so I made some minor changes.

**Comment by anb0s** [comment]
Thanks, i've just tried the Luna and Mars editions and all of them shows the EasyShell menu. So you have the preference page of EasyShell --> plugin is loaded. I've no idea how to catch this error, why the menus are not there!?

I've a test build with EasyShell 1.5 (inofficial) and and the beta of 2.0 (complete new rewrite of easyshell).
If you want to check them out: update site: http://anb0s.github.io/EasyShell/testing
see #68 too...

**Comment by hydrian** [comment]
I don't care what version I use, as long at it works for me. :-) I didn't even know 1.5 was Luna compatible. I assumed that 1.4 was the last version to support Luna because of it's age.

**Comment by hydrian** [comment]
2.0.0.v20160726-2133 Seems to work fine.

**Comment by anb0s** [comment]
Thanks, so i will set to fixed with 2.0.
